import { drawMoriaScenes } from './draw-moria-scenes.mjs';
import { roomOpenings } from './moria-geometry.mjs';

// Original vector engraving. All coordinates describe an imagined elevation,
// not Tolkien's surveyed geography. Generated by npm run generate.
export function drawMoria() {
  const s=[];
  let seed=7019;
  const random=()=>{seed=(seed*1664525+1013904223)>>>0;return seed/4294967296;};
  const n=v=>Math.round(v*10)/10;
  const path=(d,attr='')=>s.push(`<path d="${d}" ${attr}/>`);
  const line=(x1,y1,x2,y2,attr='')=>path(`M${n(x1)} ${n(y1)}L${n(x2)} ${n(y2)}`,attr);
  const rect=(x,y,w,h,attr='')=>s.push(`<rect x="${n(x)}" y="${n(y)}" width="${n(w)}" height="${n(h)}" ${attr}/>`);
  const text=(x,y,value,attr='')=>s.push(`<text x="${x}" y="${y}" ${attr}>${value}</text>`);
  const mountain='M88 531L135 486 170 489 228 421 268 430 310 363 351 351 397 247 432 209 454 153 491 213 520 230 555 299 594 272 632 287 679 208 701 208 733 166 763 173 813 91 851 141 870 133 925 240 956 251 991 225 1041 239 1083 174 1125 234 1154 256 1187 330 1220 336 1246 401 1281 403 1338 473 1383 492 1421 545L1400 619 1424 698 1388 781 1410 849 1353 914 1269 932 1186 920 1079 945 990 927 900 945 801 931 741 950 650 926 544 940 457 925 386 940 277 919 202 923 116 874 98 784 112 701 90 636Z';
  s.push(`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1500 1000" width="3000" height="2000" role="img" aria-labelledby="title desc">
<title id="title">Khazad-dûm — an imagined dwarven survey</title>
<desc id="desc">A detailed pen-and-ink west–east cutaway of Moria, with seven terraces of halls, branching mines, a great chasm and an underground lake. Orc patrols, a cave troll, a drummer, and the Balrog confronting Gandalf appear as small ink vignettes. Architectural forms, scenes and passage positions are artistic reconstructions.</desc>
<defs>
 <pattern id="rock" width="17" height="19" patternUnits="userSpaceOnUse"><path d="M-4 8L5-1M0 18L17 1M11 24L21 14" stroke="#8b7756" stroke-width=".4" opacity=".24"/><path d="M2 8l3 2m8 3 2-1" stroke="#8b7756" stroke-width=".5" opacity=".3"/></pattern>
 <pattern id="masonry" width="22" height="12" patternUnits="userSpaceOnUse"><path d="M0 0H22M0 6H22M0 12H22M11 0V6M3 6V12" fill="none" stroke="#69543a" stroke-width=".5" opacity=".45"/></pattern>
 <pattern id="dark" width="5" height="5" patternUnits="userSpaceOnUse"><path d="M0 0L5 5M5 0L0 5" stroke="#171d1b" stroke-width=".5" opacity=".28"/></pattern>
 <pattern id="water" width="48" height="12" patternUnits="userSpaceOnUse"><path d="M0 3h18m7 0h14M9 8h25m4 0h10" stroke="#647d78" stroke-width=".65" opacity=".7"/></pattern>
 <linearGradient id="stone" x2="0" y2="1"><stop stop-color="#ded0ae"/><stop offset="1" stop-color="#c3ad86"/></linearGradient>
 <linearGradient id="hall-light" x2="0" y2="1"><stop stop-color="#4f4939"/><stop offset=".55" stop-color="#b2a07b"/><stop offset="1" stop-color="#e0cfaa"/></linearGradient>
 <linearGradient id="abyss" x2="0" y2="1"><stop stop-color="#4e4b3d"/><stop offset="1" stop-color="#252d2a"/></linearGradient>
 <clipPath id="mountain"><path d="${mountain}"/></clipPath>
 <g id="lamp"><path d="M0-5v5m-3 0h6l-1 4h-4z" fill="#987b42" stroke="#4d422e" stroke-width=".7"/><path d="M0 0v3" stroke="#f5e2aa"/></g>
 <g id="door"><path d="M-7 0v-18l4-5h6l4 5V0" fill="#3c4036" stroke="#4a3c29" stroke-width="1.4"/><path d="M-10 0v-20l6-6h8l6 6V0M-2-21V0m4-21V0" fill="none" stroke="#b8a581" stroke-width=".7"/><path d="M-3-12h6" stroke="#b7a078" stroke-width=".6"/></g>
 <g id="pillar"><path d="M-12 0h24v5H8l-2 7v59l3 5h4v6h-26v-6h4l3-5V12l-2-7h-4Z" fill="#c3b08a" stroke="#4c422f" stroke-width="1.2"/><path d="M-12 3h24M-8 8h16M-6 15H6M-6 67H6M-9 76H9M-2 15v52m5-52v52" stroke="#705b3e" stroke-width=".65" fill="none"/><path d="M-6 18l12 12-12 12 12 12-12 12M6 18L-6 30 6 42-6 54 6 66" fill="none" stroke="#9a835c" stroke-width=".55"/><path d="M6 13v57l3 6h4v6H4V12" fill="#786449" opacity=".34"/></g>
</defs>`);
  rect(0,0,1500,1000,'fill="#efe3c6"');
  // Specks are static vector marks: no raster textures or expensive SVG filters.
  let specks='';for(let i=0;i<1900;i++){const x=n(random()*1500),y=n(random()*1000);specks+=`M${x} ${y}h${n(.2+random()*.7)}`;}
  path(specks,'stroke="#9e8960" stroke-width=".6" opacity=".14"');
  rect(22,22,1456,956,'fill="none" stroke="#88704b" stroke-width="1.1"');
  rect(28,28,1444,944,'fill="none" stroke="#b19a70" stroke-width=".55"');
  for(const [x,y,r] of [[37,37,0],[1463,37,90],[1463,963,180],[37,963,270]]){
    s.push(`<g transform="translate(${x} ${y}) rotate(${r})" fill="none" stroke="#80643e" stroke-width="1"><path d="M0 45V0h45M7 38V7h31M0 17l17-17 17 17-17 17zM7 17 17 7l10 10-10 10zM0 45h7v-7h38V0"/></g>`);
  }
  // Air around the summits keeps the dense underground plate legible.
  text(85,91,'KHAZAD–DÛM','font-family="Georgia,serif" font-size="25" letter-spacing="5" fill="#695236"');
  text(87,112,'THE HALLS OF DURIN’S FOLK','font-family="Georgia,serif" font-size="8" letter-spacing="2.8" fill="#8b7451"');
  line(87,124,352,124,'stroke="#a18a63" stroke-width=".7"');
  text(1398,90,'WEST–EAST ELEVATION','text-anchor="end" font-family="Georgia,serif" font-size="9" letter-spacing="2" fill="#806846"');
  text(1398,108,'An imagined survey of the mountain realm','text-anchor="end" font-family="Georgia,serif" font-size="10" font-style="italic" fill="#927c57"');
  // Exterior contours and ridges.
  path(mountain,'fill="url(#stone)" stroke="#5c513c" stroke-width="1.8" stroke-linejoin="round"');
  path(mountain,'fill="url(#rock)"');
  const ridges=[[[454,153],[445,240],[400,304],[370,398],[278,472]],[[454,153],[481,258],[524,304],[540,354]],[[813,91],[795,189],[738,251],[718,300]],[[813,91],[837,187],[886,263],[900,300]],[[1083,174],[1078,245],[1115,312],[1190,404]],[[1083,174],[1040,291],[982,328]],[[351,351],[343,410],[278,489]],[[1220,336],[1214,401],[1281,476]]];
  for(const points of ridges){
    const d=points.map(([x,y],i)=>`${i?'L':'M'}${x} ${y}`).join('');path(d,'fill="none" stroke="#675840" stroke-width="1.3"');
    let h='';for(let i=1;i<points.length;i++){const [ax,ay]=points[i-1],[bx,by]=points[i];for(let t=.09;t<1;t+=.075){const x=ax+(bx-ax)*t,y=ay+(by-ay)*t;const len=7+random()*27;h+=`M${n(x+2)} ${n(y+1)}l${n(len*.7)} ${n(len)}M${n(x-3)} ${n(y+3)}l${n(-len*.35)} ${n(len*.8)}`;}}path(h,'fill="none" stroke="#776245" stroke-width=".65" opacity=".72"');
  }
  // Slender rock faces and broken contour hatching give the peaks volume.
  for(const [x,y,spread,rise]of [[454,162,65,141],[813,103,77,174],[1083,184,59,150]]){
    for(let j=0;j<40;j++){
      const t=j/40,len=rise*(.35+.65*t),sx=x+spread*t*.8,sy=y+rise*t*.74;
      path(`M${n(sx)} ${n(sy)}l${n(7+random()*5)} ${n(len*.22)}-${n(2+random()*5)} ${n(len*.11)} ${n(5+random()*10)} ${n(len*.22)}`,'fill="none" stroke="#796442" stroke-width=".7" opacity=".6"');
    }
  }
  // Irregular strata, fractures and mineral seams continue behind the masonry.
  s.push('<g clip-path="url(#mountain)" fill="none">');
  for(let i=0;i<39;i++){
    const y=310+i*16;let d=`M70 ${y}`;
    for(let x=110;x<1450;x+=35)d+=`l35 ${n((random()-.49)*14)}`;
    path(d,`stroke="#715e40" stroke-width="${i%5===0?'.9':'.4'}" opacity="${i%5===0?'.3':'.19'}"`);
  }
  for(let i=0;i<155;i++){
    const x=115+random()*1270,y=325+random()*570;
    path(`M${n(x)} ${n(y)}l${n(random()*14-7)} 12-5 9 8 13-3 8`,'stroke="#766346" stroke-width=".55" opacity=".42"');
  }
  s.push('</g>');
  // The long natural chasm is cut before the halls, so the bridge sits above it.
  const chasm='M1167 605Q1187 595 1209 604Q1195 627 1214 650L1206 678Q1228 700 1221 721L1210 744Q1220 760 1238 774L1223 803Q1215 819 1228 838L1214 851Q1201 882 1178 889L1130 902 1101 888Q1131 868 1135 853L1161 830Q1177 811 1166 795L1157 777Q1164 755 1180 741L1168 719Q1162 700 1175 681L1164 653Q1151 633 1167 611Z';
  path(chasm,'fill="url(#abyss)" stroke="#443e2f" stroke-width="2"');
  path(chasm,'fill="url(#dark)"');
  path('M1192 610l16 28-12 24 14 47-10 30 14 34-9 31M1172 615l8 30-7 25 10 28-7 20','fill="none" stroke="#a59770" stroke-width=".8" opacity=".5"');
  // Passages have stone shoulders, a shadowed roof and a pale walking surface.
  function tunnels(routes){
    // Paint each stone layer across the whole network before its inset layer:
    // T-junctions then share an open interior instead of crossing wall strokes.
    for(const [color,inset] of [['#796446',5],['#d4bd91',3],['#766447',0],['#b6a17a',-3]]){
      for(const [d,width] of routes)path(d,`fill="none" stroke="${color}" stroke-width="${width+inset}" stroke-linejoin="bevel"`);
    }
  }
  function stairs(x,y,w,rise,steps=16){
    const dx=w/steps,dy=rise/steps;let d=`M${x} ${y}`;
    for(let i=0;i<steps;i++)d+=`h${n(dx)}v${n(dy)}`;
    path(d,'fill="none" stroke="#e3d2aa" stroke-width="2"');
    path(d,'fill="none" stroke="#4d422f" stroke-width=".65"');
  }
  const minePaths=[
    'M313 632V717H247L204 750H158',
    'M396 695V746H516L546 777H615',
    'M265 719V794H387L416 765H493',
    'M203 751V829H338V861H475',
    'M516 749V815H587V838H658',
    'M385 796V842H431',
    'M396 746V785',
    'M630 708V762H681V813H734',
    'M942 750V812H1074V841H1114',
    'M247 794H170V859H212',
    'M735 739V776H793',
    'M1000 776H1110V741H1143',
    'M1125 590V680H1021V697H989'
  ];
  const passages=[
    ['M149 518H238L340 449H446L511 383H647',17],
    ['M356 449V492H574L643 453H1129',12],
    ['M507 383V343H646',10],
    ['M923 382H967V333H1010',12],
    ['M1060 337H1119V430L1063 472V550',12],
    ['M445 459V557H575V622H950',13],
    ['M238 518H340V561H440',11],
    ['M579 492V548H761L806 505H963',12],
    ['M330 637H528V698H650',12],
    ['M950 594V656H823V706H650',12],
    ['M1270 604L1317 534H1389',17],
    ['M700 640V737H941V777H1071',10],
    ['M1160 451H1264V580L1270 604',10],
    ['M924 457V505',10],
    ['M585 324V343',9],
    ['M927 305V324H980V337H1010',9],
    ['M740 515V548',9],
    ['M761 548V576H744',9],
    ['M900 645V656',9]
  ];
  tunnels([...passages,...minePaths.map(d=>[d,7])]);
  stairs(239,525,101,-69,23);stairs(445,455,65,-66,18);stairs(576,498,65,-40,17);stairs(968,384,38,-46,16);stairs(1120,440,-58,40,18);stairs(1265,608,53,-74,22);stairs(762,555,43,-47,14);
  // A winding carved stair wraps a stone core. Broken rock margins replace
  // the former straight shaft; rear flights recede into hatched shadow.
  const stairCentre=y=>y<180?813+(Math.sin(y/76)*12-3)*Math.max(0,(y-117)/63):810+Math.sin(y/76)*12;
  let left='',right='';
  for(let y=117;y<=848;y+=13){
    const cx=stairCentre(y),r=14+(y%39===0?3:0);
    left+=`${left?'L':'M'}${n(cx-r)} ${y}`;
    right=`L${n(cx+r)} ${y}`+right;
  }
  const shaft=left+right+'Z';
  path(shaft,'fill="#655d45" stroke="#715a39" stroke-width="1.3"');
  path(shaft,'fill="url(#dark)"');
  for(let y=123;y<839;y+=26){
    const cx=stairCentre(y);
    path(`M${n(cx-13)} ${y}Q${n(cx)} ${y+10} ${n(cx+13)} ${y+4}L${n(cx+13)} ${y+8}Q${n(cx)} ${y+14} ${n(cx-13)} ${y+4}Z`,'fill="#97815a" stroke="#3e3e2e" stroke-width=".5"');
    path(`M${n(cx+13)} ${y+7}Q${n(cx)} ${y+14} ${n(cx-13)} ${y+22}v4Q${n(cx)} ${y+18} ${n(cx+13)} ${y+11}Z`,'fill="#dbc69b" stroke="#58482e" stroke-width=".7"');
    for(let k=1;k<10;k++){
      const t=k/10,x=cx+13-26*t,sy=y+7+15*t;
      line(x,sy,x,sy+4,'stroke="#79613c" stroke-width=".65"');
    }
    path(`M${n(cx-2)} ${y-1}v26h4v-26`,'fill="#b39a6d" stroke="#695538" stroke-width=".5"');
  }
  // Reusable orthographic chambers; outlines and block courses remain fine at 6×.
  let hallNumber=0;
  const chambers=[];
  function hall(x,y,w,h,bays=5,grand=false){
    const id='hall-'+hallNumber++,arched=!grand&&hallNumber%3===0;
    const roof=arched?`M${x} ${y+h}V${y+18}Q${x+w/2} ${y-13} ${x+w} ${y+18}V${y+h}Z`:`M${x} ${y+h}V${y+15}L${x+15} ${y}H${x+w-15}L${x+w} ${y+15}V${y+h}Z`;
    chambers.push({x,y,w,h,outline:[[x,y+h],[x,y+15],[x+15,y],[x+w-15,y],[x+w,y+15],[x+w,y+h]]});
    path(roof,'fill="#d5bf95" stroke="#806644" stroke-width="9" stroke-linejoin="round"');
    path(roof,'fill="url(#hall-light)" stroke="#53442e" stroke-width="1.1"');
    s.push(`<clipPath id="${id}"><path d="${roof}"/></clipPath><g clip-path="url(#${id})">`);
    // The back wall is ink-hatched, with recessed arcades rather than a row of doors.
    let shade='';for(let bx=x-25;bx<x+w+30;bx+=3.5)shade+=`M${n(bx)} ${y}l${n(h*.33)} ${n(h*.55)}`;
    path(shade,'fill="none" stroke="#4a402c" stroke-width=".45" opacity=".33"');
    const cell=w/bays;
    for(let i=0;i<bays;i++){
      const bx=x+i*cell,mid=bx+cell/2;
      if(grand){
        path(`M${n(bx+5)} ${y+h}V${y+23}L${n(bx+cell*.27)} ${y+9}H${n(bx+cell*.73)}L${n(bx+cell-5)} ${y+23}V${y+h}`,'fill="none" stroke="#d6c097" stroke-width="1" opacity=".7"');
        s.push(`<use href="#lamp" x="${n(mid)}" y="${y+33}"/>`);
        for(let k=0;k<3;k++)line(mid-5+k*5,y+7,mid-5+k*5,y+13,'stroke="#ba9f6e" stroke-width=".7"');
      } else if(hallNumber%3===0){
        path(`M${n(mid-cell*.28)} ${y+h-2}V${y+17}Q${n(mid)} ${y+5} ${n(mid+cell*.28)} ${y+17}V${y+h-2}`,'fill="#73654b" stroke="#c5ae80" stroke-width=".8"');
        line(mid-cell*.25,y+h-8,mid+cell*.25,y+h-8,'stroke="#b29a6f" stroke-width="1"');
      } else if(hallNumber%3===1){
        rect(mid-cell*.27,y+h-15,cell*.54,12,'fill="#ab926a" stroke="#725a37" stroke-width=".65"');
        path(`M${n(mid-cell*.27)} ${y+h-15}l4-4h${n(cell*.54-8)}l4 4`,'fill="#ccb58b" stroke="#725a37" stroke-width=".65"');
        line(mid,y+h-15,mid,y+h-3,'stroke="#806644" stroke-width=".65"');
      } else {
        rect(mid-cell*.25,y+10,cell*.5,h-15,'fill="#847352" stroke="#b59b70" stroke-width=".7"');
        for(let shelf=y+15;shelf<y+h-6;shelf+=6){
          line(mid-cell*.25,shelf,mid+cell*.25,shelf,'stroke="#d5bc8f" stroke-width=".8"');
          for(let k=0;k<4;k++)line(mid-cell*.18+k*cell*.12,shelf-4,mid-cell*.18+k*cell*.12,shelf,'stroke="#c0a373" stroke-width=".8"');
        }
      }
    }
    if(grand){for(let i=1;i<bays;i++)s.push(`<use href="#pillar" transform="translate(${n(x+i*cell)} ${y+4}) scale(.86 ${n((h-4)/82)})"/>`);}
    else for(let i=1;i<bays;i++){
      const px=x+i*cell;
      path(`M${n(px-4)} ${y+4}h8l-2 4v${h-11}h3v3h-10v-3h3V${y+8}Z`,'fill="#c8af82" stroke="#655033" stroke-width=".7"');
    }
    // Floor jointing creates depth without switching to an isometric viewpoint.
    for(let bx=x;bx<x+w;bx+=11)line(bx,y+h-4,bx+4,y+h,'stroke="#9a7d50" stroke-width=".55"');
    s.push('</g>');
    path(`M${x-4} ${y+h+1}h${w+8}m-${w+8} 4h${w+8}`,'fill="none" stroke="#6b5434" stroke-width=".8"');
    if(grand){
      path(`M${x-3} ${y-7}H${x+w+3}M${x-3} ${y-12}H${x+w+3}`,'stroke="#806641" stroke-width=".8"');
      for(let bx=x+5;bx<x+w-5;bx+=14)path(`M${bx} ${y-7}l5-5 5 5`,'fill="none" stroke="#876e46" stroke-width=".7"');
    }
  }
  // Upper dwellings, galleries and the great North-end hall.
  hall(548,304,174,28,7);hall(881,283,91,28,4);
  hall(634,339,327,78,8,true);
  // Narrow daylight shafts are projected onto this elevation.
  for(const [x,top] of [[690,257],[924,273]]){
    path(`M${x} ${top}v65l-6 15h13l-6-15V${top}`,'fill="#ebdbb8" stroke="#7b6748" stroke-width=".65"');
    path(`M${x-1} ${top}v${338-top}`,'stroke="#f8eccd" stroke-width="1.4"');
  }
  // Mazarbul: a small distinct room with the tomb and shelves of records.
  hall(1000,303,87,49,1,true);
  rect(1018,343,35,5,'fill="#dbcfb0" stroke="#51422f" stroke-width=".8"');
  path('M1021 341l4-5h25l3 5z','fill="#e4d9bd" stroke="#51422f" stroke-width=".9"');
  line(1027,338,1048,338,'stroke="#8b7652" stroke-width=".5"');
  for(let y=316;y<=334;y+=6){line(1063,y,1080,y,'stroke="#d3c19a" stroke-width="1.1"');for(let x=1065;x<1080;x+=3)line(x,y-4,x,y,'stroke="#b7a17b" stroke-width=".7"');}
  hall(467,432,233,41,8);hall(854,434,176,35,6);hall(1086,435,87,28,3);
  hall(327,500,184,35,7);hall(618,492,132,30,5);hall(896,493,99,29,4);
  hall(394,550,130,35,5);hall(610,551,175,40,6);
  // Old Moria: second hall, bridge and eastern first hall.
  hall(936,535,230,69,6,true);
  path('M1162 603Q1215 594 1276 603L1276 608Q1215 602 1162 609Z','fill="#dfcca4" stroke="#493d2b" stroke-width="1.2"');
  path('M1167 610Q1218 640 1272 610','fill="none" stroke="#6f5c40" stroke-width="1"');
  for(let x=1171;x<1273;x+=8)line(x,602+Math.abs(x-1215)*.045,x+1,606+Math.abs(x-1215)*.035,'stroke="#8c7049" stroke-width=".6"');
  hall(1311,502,79,34,3,true);
  hall(312,607,188,32,7);hall(573,612,183,39,6);hall(859,624,83,31,3);
  hall(384,673,111,29,4);hall(598,687,94,28,4);hall(889,727,111,31,4);
  // Cut only where a corridor actually crosses a chamber outline. Keeping
  // portals tied to the route geometry avoids decorative doors into solid rock.
  for(const {x,y,dx,dy,width,room}of roomOpenings([...passages,...minePaths.map(d=>[d,7])],chambers)){
    const half=(width-3)/2;
    path(`M${n(x-dx*6)} ${n(y-dy*6)}l${n(dx*12)} ${n(dy*12)}`,`fill="none" stroke="#b6a17a" stroke-width="${width-3}"`);
    for(const side of [-1,1]){
      const px=-dy*half*side,py=dx*half*side;
      line(x-dx*6+px,y-dy*6+py,x+dx*6+px,y+dy*6+py,'stroke="#796446" stroke-width=".5"');
    }
    if(Math.abs(dy)<.01 && (Math.abs(x-room.x)<1||Math.abs(x-room.x-room.w)<1)){
      const direction=x<room.x+room.w/2?1:-1,drop=room.y+room.h-y-width/2;
      if(drop>3&&drop<35)stairs(n(x+direction*5),n(y+width/2-1),direction*15,n(drop),Math.ceil(drop/2));
    }
  }
  // Small winding stairs and landings make the vertical connections readable.
  for(const [x,y,height]of [[1119,356,68],[1063,477,57],[445,482,56],[575,580,37],[528,649,43],[823,663,37]]){
    for(let sy=y;sy<y+height;sy+=14){stairs(x-4,sy,8,6,5);stairs(x+4,sy+7,-8,6,5);}
  }
  // Western workshops: anvils, cisterns, grain jars and racks suggest lived-in craft.
  for(const [x,y] of [[335,632],[389,632],[446,632]]){
    path(`M${x-8} ${y-9}h17l-5 4h-3v5h-6v-5l-3-1z`,'fill="#716149" stroke="#4d412f" stroke-width=".7"');
    rect(x-5,y+1,12,4,'fill="#aa8b5c" stroke="#5f4d32" stroke-width=".65"');
  }
  for(let i=0;i<7;i++){
    const x=584+i*21;path(`M${x} 637q-2-8 4-10v-3h5v3q6 3 4 10z`,'fill="#b8a079" stroke="#5d4c32" stroke-width=".6"');
  }
  // The branching workings: narrow seams, dead ends, winches, timber supports.
  for(const [x,y]of [[234,717],[273,794],[311,794],[436,746],[477,746],[433,861],[538,815],[647,762],[1029,812],[1082,776],[188,829]]){
    path(`M${x-4} ${y+4}v-10h8v10M${x-6} ${y-6}h12M${x-4} ${y-3}l3-3m5 3-3-3`,'fill="none" stroke="#4b3e29" stroke-width="1"');
  }
  for(const [x,y]of [[158,750],[615,777],[493,765],[475,861],[658,838],[431,842],[734,813],[1114,841],[212,859],[793,776],[1143,741],[989,697]]){
    path(`M${x-2} ${y-5}l4 2-2 3 3 3-5 3`,'fill="none" stroke="#5e4d33" stroke-width="1.1"');
    for(let i=0;i<5;i++)line(x+4+i*2,y-6+random()*12,x+7+i*2,y-3+random()*10,'stroke="#8a7049" stroke-width=".65"');
  }
  // Ore veins distinguish the deep workings from orderly dressed-stone halls.
  for(const [x,y]of [[335,752],[487,798],[564,872],[211,873],[1040,873]]){
    path(`M${x-23} ${y+9}l12-7 9 5 12-14 8 4 11-9M${x+3} ${y+3}l4 9 13 5M${x-10} ${y+2}l-2-12`,'fill="none" stroke="#6c827c" stroke-width="1.7"');
    path(`M${x-19} ${y+12}l12-7 9 5 12-14 8 4 11-9`,'fill="none" stroke="#dddcc0" stroke-width=".7"');
  }
  // Bottommost natural cavern, its shore and still, cold water.
  const cavern='M657 839L690 823 724 833 746 812 773 828 798 812 825 834 854 821 877 840 902 830 925 851 958 840 980 859 1024 847 1051 872 1083 865 1106 890 1073 914 1010 911 970 921 922 914 870 929 821 917 770 924 723 909 687 913 650 890 635 867Z';
  path(cavern,'fill="url(#abyss)" stroke="#584a34" stroke-width="1.6"');
  path(cavern,'fill="url(#dark)"');
  for(const [x,y,len]of [[691,824,24],[749,816,25],[799,819,34],[854,824,20],[901,835,23],[960,847,21],[1022,851,26]]){
    path(`M${x-6} ${y}l6 ${len} 5-${len-2}`,'fill="#a79773" stroke="#63543c" stroke-width=".7"');
  }
  const water='M648 883Q713 865 757 876T861 879T969 879T1097 891L1070 908 1010 905 970 915 922 908 870 922 821 911 770 918 723 903 687 906Z';
  path(water,'fill="#81948a" stroke="#b2b297" stroke-width=".8"');path(water,'fill="url(#water)"');
  for(let i=0;i<42;i++){
    const x=655+random()*426,y=881+random()*18;
    line(x,y,x+4+random()*15,y,'stroke="#c1c6aa" stroke-width=".5" opacity=".7"');
  }
  // A few fallen blocks, never a tiled repetition across the void.
  for(const [x,y]of [[724,901],[750,908],[995,902],[683,895],[1091,891]])path(`M${x} ${y}l7-9 9 2 3 6-4 4z`,'fill="#a18f6d" stroke="#534731" stroke-width=".8"');
  // West door and the still pool before its threshold.
  path('M61 544Q88 531 116 541T153 547L142 560Q101 565 65 556Z','fill="#8ea399" stroke="#738573" stroke-width=".8"');
  path('M70 549h34m5 2h27m-57 5h43m-26-13h15','stroke="#c9d0b0" stroke-width=".9"');
  path('M134 532v-30q0-21 16-21t16 21v30','fill="#424b40" stroke="#5c5038" stroke-width="1.4"');
  path('M140 530v-28q0-14 10-14t10 14v28M150 489v40','fill="none" stroke="#b4c4ac" stroke-width=".9"');
  path('M143 508l7-8 7 8m-7-8v18m-6-5 6-5 6 5M145 523h10','fill="none" stroke="#c2ceb2" stroke-width=".7"');
  for(const [x,y]of [[127,492],[176,487]]){
    path(`M${x} ${y+50}q-6-20 0-48m0 17-10-12m9 22 13-16m-12 29-10-8`,'fill="none" stroke="#6e684d" stroke-width="1.1"');
  }
  // Eastern gate: angular dwarf-carved portal, masonry lintel and approach.
  path('M1383 541v-47l9-10h15l9 10v47','fill="#424538" stroke="#58472f" stroke-width="2"');
  path('M1388 540v-43l7-7h9l7 7v43M1382 496h36M1380 544h40','fill="none" stroke="#bea981" stroke-width="1.4"');
  for(let y=500;y<538;y+=8){line(1380,y,1386,y,'stroke="#6e5b3e" stroke-width=".8"');line(1413,y,1418,y,'stroke="#6e5b3e" stroke-width=".8"');}
  path('M1417 541l18 8 5 10 19 4M1416 546l12 9 6 10 24 4','fill="none" stroke="#806d4b" stroke-width="1.1"');
  // Durin's Tower, a small crown at the summit of Celebdil.
  s.push('<g stroke="#5d4b31" stroke-width="1" fill="#d8c8a2">');
  path('M799 114V76h-4V62h7v6h7v-6h7v6h7v-6h7v14h-4v38Z');
  path('M795 77h35M799 82h27M799 109h27','fill="none"');
  path('M809 109V93l4-4 4 4v16','fill="#5c5740"');
  path('M804 85V77m18 8v-8M799 100h8m12 0h7M804 109v-8','fill="none" stroke-width=".6"');
  s.push('</g>');
  s.push(drawMoriaScenes());
  // Survey annotations occupy empty rock and margins, separate from live pins.
  text(1092,293,'THE UPPER HALLS','font-family="Georgia,serif" font-size="9" letter-spacing="2.2" fill="#756343" transform="rotate(12 1092 293)"');
  text(175,681,'WESTERN WORKINGS','font-family="Georgia,serif" font-size="8" letter-spacing="1.5" fill="#746043"');
  text(1045,716,'THE LOWER DEEPS','font-family="Georgia,serif" font-size="8" letter-spacing="1.5" fill="#776447"');
  text(860,957,'Beneath the roots of the mountains','font-family="Georgia,serif" font-size="10" font-style="italic" text-anchor="middle" fill="#776447"');
  text(71,935,'DRAWN IN THE MANNER OF','font-family="Georgia,serif" font-size="7" letter-spacing="1.5" fill="#8b7452"');
  text(71,950,'the stonewrights of Khazad-dûm','font-family="Georgia,serif" font-size="11" font-style="italic" fill="#6e5638"');
  text(1430,953,'PLATE I  ·  NOT TO SCALE','text-anchor="end" font-family="Georgia,serif" font-size="8" letter-spacing="1.5" fill="#8b7452"');
  s.push('</svg>\n');
  return s.join('\n');
}
